/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "code.v:1" *)
module apb(pclk, presetn, psel, pwrite, penable, pwdata, paddr, prdata0, prdata1, prdata2, data, pready);
  (* src = "code.v:20" *)
  wire [3:0] _000_;
  (* src = "code.v:20" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  (* src = "code.v:20" *)
  wire _046_;
  (* src = "code.v:20" *)
  wire _047_;
  (* src = "code.v:20" *)
  wire _048_;
  (* src = "code.v:20" *)
  wire _049_;
  (* src = "code.v:20" *)
  wire _050_;
  (* src = "code.v:16" *)
  wire _051_;
  (* src = "code.v:16" *)
  wire _052_;
  (* src = "code.v:16" *)
  wire _053_;
  (* src = "code.v:16" *)
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  (* src = "code.v:7" *)
  wire _077_;
  (* src = "code.v:12" *)
  wire _078_;
  (* src = "code.v:12" *)
  wire _079_;
  (* src = "code.v:12" *)
  wire _080_;
  (* src = "code.v:12" *)
  wire _081_;
  (* src = "code.v:13" *)
  wire _082_;
  (* src = "code.v:13" *)
  wire _083_;
  (* src = "code.v:13" *)
  wire _084_;
  (* src = "code.v:13" *)
  wire _085_;
  (* src = "code.v:14" *)
  wire _086_;
  (* src = "code.v:14" *)
  wire _087_;
  (* src = "code.v:14" *)
  wire _088_;
  (* src = "code.v:14" *)
  wire _089_;
  (* src = "code.v:5" *)
  wire _090_;
  (* src = "code.v:5" *)
  wire _091_;
  (* src = "code.v:9" *)
  wire _092_;
  (* src = "code.v:9" *)
  wire _093_;
  (* src = "code.v:9" *)
  wire _094_;
  (* src = "code.v:9" *)
  wire _095_;
  (* src = "code.v:6" *)
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  (* src = "code.v:16" *)
  output [3:0] data;
  (* src = "code.v:10" *)
  input [3:0] paddr;
  (* src = "code.v:2" *)
  input pclk;
  (* src = "code.v:7" *)
  input penable;
  (* src = "code.v:12" *)
  input [3:0] prdata0;
  (* src = "code.v:13" *)
  input [3:0] prdata1;
  (* src = "code.v:14" *)
  input [3:0] prdata2;
  (* src = "code.v:17" *)
  output pready;
  (* src = "code.v:3" *)
  input presetn;
  (* src = "code.v:5" *)
  input [1:0] psel;
  (* src = "code.v:9" *)
  input [3:0] pwdata;
  (* src = "code.v:6" *)
  input pwrite;
  INV_X1 _102_ (
    .A(_091_),
    .ZN(_055_)
  );
  INV_X1 _103_ (
    .A(_092_),
    .ZN(_056_)
  );
  INV_X1 _104_ (
    .A(_093_),
    .ZN(_057_)
  );
  INV_X1 _105_ (
    .A(_094_),
    .ZN(_058_)
  );
  INV_X1 _106_ (
    .A(_095_),
    .ZN(_059_)
  );
  OAI21_X1 _107_ (
    .A(_077_),
    .B1(_090_),
    .B2(_091_),
    .ZN(_060_)
  );
  INV_X1 _108_ (
    .A(_060_),
    .ZN(_050_)
  );
  AND2_X1 _109_ (
    .A1(_051_),
    .A2(_060_),
    .ZN(_061_)
  );
  OAI21_X1 _110_ (
    .A(_091_),
    .B1(_096_),
    .B2(_086_),
    .ZN(_062_)
  );
  OAI211_X1 _111_ (
    .A(_055_),
    .B(_090_),
    .C1(_096_),
    .C2(_082_),
    .ZN(_063_)
  );
  AOI221_X1 _112_ (
    .A(_060_),
    .B1(_062_),
    .B2(_063_),
    .C1(_096_),
    .C2(_056_),
    .ZN(_064_)
  );
  OR2_X1 _113_ (
    .A1(_061_),
    .A2(_064_),
    .ZN(_046_)
  );
  AND2_X1 _114_ (
    .A1(_052_),
    .A2(_060_),
    .ZN(_065_)
  );
  OAI211_X1 _115_ (
    .A(_055_),
    .B(_090_),
    .C1(_096_),
    .C2(_083_),
    .ZN(_066_)
  );
  OAI21_X1 _116_ (
    .A(_091_),
    .B1(_096_),
    .B2(_087_),
    .ZN(_067_)
  );
  AOI221_X1 _117_ (
    .A(_060_),
    .B1(_066_),
    .B2(_067_),
    .C1(_057_),
    .C2(_096_),
    .ZN(_068_)
  );
  OR2_X1 _118_ (
    .A1(_065_),
    .A2(_068_),
    .ZN(_047_)
  );
  AND2_X1 _119_ (
    .A1(_053_),
    .A2(_060_),
    .ZN(_069_)
  );
  OAI211_X1 _120_ (
    .A(_055_),
    .B(_090_),
    .C1(_096_),
    .C2(_084_),
    .ZN(_070_)
  );
  OAI21_X1 _121_ (
    .A(_091_),
    .B1(_096_),
    .B2(_088_),
    .ZN(_071_)
  );
  AOI221_X1 _122_ (
    .A(_060_),
    .B1(_070_),
    .B2(_071_),
    .C1(_058_),
    .C2(_096_),
    .ZN(_072_)
  );
  OR2_X1 _123_ (
    .A1(_069_),
    .A2(_072_),
    .ZN(_048_)
  );
  AND2_X1 _124_ (
    .A1(_054_),
    .A2(_060_),
    .ZN(_073_)
  );
  OAI211_X1 _125_ (
    .A(_055_),
    .B(_090_),
    .C1(_096_),
    .C2(_085_),
    .ZN(_074_)
  );
  OAI21_X1 _126_ (
    .A(_091_),
    .B1(_096_),
    .B2(_089_),
    .ZN(_075_)
  );
  AOI221_X1 _127_ (
    .A(_060_),
    .B1(_074_),
    .B2(_075_),
    .C1(_059_),
    .C2(_096_),
    .ZN(_076_)
  );
  OR2_X1 _128_ (
    .A1(_073_),
    .A2(_076_),
    .ZN(_049_)
  );
  (* src = "code.v:20" *)
  DFFR_X1 _129_ (
    .CK(pclk),
    .D(_000_[0]),
    .Q(data[0]),
    .QN(_097_),
    .RN(presetn)
  );
  (* src = "code.v:20" *)
  DFFR_X1 _130_ (
    .CK(pclk),
    .D(_000_[1]),
    .Q(data[1]),
    .QN(_098_),
    .RN(presetn)
  );
  (* src = "code.v:20" *)
  DFFR_X1 _131_ (
    .CK(pclk),
    .D(_000_[2]),
    .Q(data[2]),
    .QN(_099_),
    .RN(presetn)
  );
  (* src = "code.v:20" *)
  DFFR_X1 _132_ (
    .CK(pclk),
    .D(_000_[3]),
    .Q(data[3]),
    .QN(_100_),
    .RN(presetn)
  );
  (* src = "code.v:20" *)
  DFFR_X1 _133_ (
    .CK(pclk),
    .D(_001_),
    .Q(pready),
    .QN(_101_),
    .RN(presetn)
  );
  assign _091_ = psel[1];
  assign _090_ = psel[0];
  assign _078_ = prdata0[0];
  assign _092_ = pwdata[0];
  assign _096_ = pwrite;
  assign _086_ = prdata2[0];
  assign _082_ = prdata1[0];
  assign _051_ = data[0];
  assign _000_[0] = _046_;
  assign _079_ = prdata0[1];
  assign _093_ = pwdata[1];
  assign _087_ = prdata2[1];
  assign _083_ = prdata1[1];
  assign _052_ = data[1];
  assign _000_[1] = _047_;
  assign _080_ = prdata0[2];
  assign _094_ = pwdata[2];
  assign _088_ = prdata2[2];
  assign _084_ = prdata1[2];
  assign _053_ = data[2];
  assign _000_[2] = _048_;
  assign _081_ = prdata0[3];
  assign _095_ = pwdata[3];
  assign _089_ = prdata2[3];
  assign _085_ = prdata1[3];
  assign _054_ = data[3];
  assign _000_[3] = _049_;
  assign _077_ = penable;
  assign _001_ = _050_;
endmodule
