/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "code.v:1" *)
module apb(pclk, presetn, psel, pwrite, penable, pwdata, paddr, prdata0, prdata1, prdata2, data, pready);
  (* src = "code.v:20" *)
  wire [3:0] _000_;
  (* src = "code.v:20" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  (* src = "code.v:20" *)
  wire _046_;
  (* src = "code.v:20" *)
  wire _047_;
  (* src = "code.v:20" *)
  wire _048_;
  (* src = "code.v:20" *)
  wire _049_;
  (* src = "code.v:20" *)
  wire _050_;
  (* src = "code.v:16" *)
  wire _051_;
  (* src = "code.v:16" *)
  wire _052_;
  (* src = "code.v:16" *)
  wire _053_;
  (* src = "code.v:16" *)
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  (* src = "code.v:7" *)
  wire _077_;
  (* src = "code.v:12" *)
  wire _078_;
  (* src = "code.v:12" *)
  wire _079_;
  (* src = "code.v:12" *)
  wire _080_;
  (* src = "code.v:12" *)
  wire _081_;
  (* src = "code.v:13" *)
  wire _082_;
  (* src = "code.v:13" *)
  wire _083_;
  (* src = "code.v:13" *)
  wire _084_;
  (* src = "code.v:13" *)
  wire _085_;
  (* src = "code.v:14" *)
  wire _086_;
  (* src = "code.v:14" *)
  wire _087_;
  (* src = "code.v:14" *)
  wire _088_;
  (* src = "code.v:14" *)
  wire _089_;
  (* src = "code.v:5" *)
  wire _090_;
  (* src = "code.v:5" *)
  wire _091_;
  (* src = "code.v:9" *)
  wire _092_;
  (* src = "code.v:9" *)
  wire _093_;
  (* src = "code.v:9" *)
  wire _094_;
  (* src = "code.v:9" *)
  wire _095_;
  (* src = "code.v:6" *)
  wire _096_;
  (* src = "code.v:16" *)
  output [3:0] data;
  (* src = "code.v:10" *)
  input [3:0] paddr;
  (* src = "code.v:2" *)
  input pclk;
  (* src = "code.v:7" *)
  input penable;
  (* src = "code.v:12" *)
  input [3:0] prdata0;
  (* src = "code.v:13" *)
  input [3:0] prdata1;
  (* src = "code.v:14" *)
  input [3:0] prdata2;
  (* src = "code.v:17" *)
  output pready;
  (* src = "code.v:3" *)
  input presetn;
  (* src = "code.v:5" *)
  input [1:0] psel;
  (* src = "code.v:9" *)
  input [3:0] pwdata;
  (* src = "code.v:6" *)
  input pwrite;
  sky130_fd_sc_hd__clkinv_1 _097_ (
    .A(_092_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__clkinv_1 _098_ (
    .A(_093_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__clkinv_1 _099_ (
    .A(_094_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__clkinv_1 _100_ (
    .A(_095_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__o21ai_0 _101_ (
    .A1(_091_),
    .A2(_090_),
    .B1(_077_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__clkinv_1 _102_ (
    .A(_059_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o21ai_0 _103_ (
    .A1(_096_),
    .A2(_086_),
    .B1(_091_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2b_1 _104_ (
    .A_N(_091_),
    .B(_090_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor2_1 _105_ (
    .A(_096_),
    .B(_082_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__o21ai_0 _106_ (
    .A1(_061_),
    .A2(_062_),
    .B1(_060_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a21oi_1 _107_ (
    .A1(_055_),
    .A2(_096_),
    .B1(_059_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__a22o_1 _108_ (
    .A1(_051_),
    .A2(_059_),
    .B1(_063_),
    .B2(_064_),
    .X(_046_)
  );
  sky130_fd_sc_hd__nor2_1 _109_ (
    .A(_096_),
    .B(_083_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__o21ai_0 _110_ (
    .A1(_096_),
    .A2(_087_),
    .B1(_091_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__o21ai_0 _111_ (
    .A1(_061_),
    .A2(_065_),
    .B1(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__a21oi_1 _112_ (
    .A1(_096_),
    .A2(_056_),
    .B1(_059_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__a22o_1 _113_ (
    .A1(_052_),
    .A2(_059_),
    .B1(_067_),
    .B2(_068_),
    .X(_047_)
  );
  sky130_fd_sc_hd__nor2_1 _114_ (
    .A(_096_),
    .B(_084_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__o21ai_0 _115_ (
    .A1(_096_),
    .A2(_088_),
    .B1(_091_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__o21ai_0 _116_ (
    .A1(_061_),
    .A2(_069_),
    .B1(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__a21oi_1 _117_ (
    .A1(_096_),
    .A2(_057_),
    .B1(_059_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a22o_1 _118_ (
    .A1(_053_),
    .A2(_059_),
    .B1(_071_),
    .B2(_072_),
    .X(_048_)
  );
  sky130_fd_sc_hd__nor2_1 _119_ (
    .A(_096_),
    .B(_085_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__o21ai_0 _120_ (
    .A1(_096_),
    .A2(_089_),
    .B1(_091_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o21ai_0 _121_ (
    .A1(_061_),
    .A2(_073_),
    .B1(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a21oi_1 _122_ (
    .A1(_096_),
    .A2(_058_),
    .B1(_059_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__a22o_1 _123_ (
    .A1(_054_),
    .A2(_059_),
    .B1(_075_),
    .B2(_076_),
    .X(_049_)
  );
  (* src = "code.v:20" *)
  sky130_fd_sc_hd__dfrtp_1 _124_ (
    .CLK(pclk),
    .D(_000_[0]),
    .Q(data[0]),
    .RESET_B(presetn)
  );
  (* src = "code.v:20" *)
  sky130_fd_sc_hd__dfrtp_1 _125_ (
    .CLK(pclk),
    .D(_000_[1]),
    .Q(data[1]),
    .RESET_B(presetn)
  );
  (* src = "code.v:20" *)
  sky130_fd_sc_hd__dfrtp_1 _126_ (
    .CLK(pclk),
    .D(_000_[2]),
    .Q(data[2]),
    .RESET_B(presetn)
  );
  (* src = "code.v:20" *)
  sky130_fd_sc_hd__dfrtp_1 _127_ (
    .CLK(pclk),
    .D(_000_[3]),
    .Q(data[3]),
    .RESET_B(presetn)
  );
  (* src = "code.v:20" *)
  sky130_fd_sc_hd__dfrtp_1 _128_ (
    .CLK(pclk),
    .D(_001_),
    .Q(pready),
    .RESET_B(presetn)
  );
  assign _091_ = psel[1];
  assign _090_ = psel[0];
  assign _078_ = prdata0[0];
  assign _092_ = pwdata[0];
  assign _096_ = pwrite;
  assign _086_ = prdata2[0];
  assign _082_ = prdata1[0];
  assign _051_ = data[0];
  assign _000_[0] = _046_;
  assign _079_ = prdata0[1];
  assign _093_ = pwdata[1];
  assign _087_ = prdata2[1];
  assign _083_ = prdata1[1];
  assign _052_ = data[1];
  assign _000_[1] = _047_;
  assign _080_ = prdata0[2];
  assign _094_ = pwdata[2];
  assign _088_ = prdata2[2];
  assign _084_ = prdata1[2];
  assign _053_ = data[2];
  assign _000_[2] = _048_;
  assign _081_ = prdata0[3];
  assign _095_ = pwdata[3];
  assign _089_ = prdata2[3];
  assign _085_ = prdata1[3];
  assign _054_ = data[3];
  assign _000_[3] = _049_;
  assign _077_ = penable;
  assign _001_ = _050_;
endmodule
